import {menuCollection} from "@/util/database";
import { MenuItem } from "@/util/models";

// export const menu = await (async function getMenu() {
//     return await menuCollection.find().toArray() as unknown as MenuItem[];
// })()

//demo data
export const menu: MenuItem[] = [
    {
        _id: '1',
        name: 'Cheeseburger',
        price: 5.99,
        category: 'Burgers',
        description: 'A delicious cheeseburger with all the fixings.',
        image: 'https://cdn.pixabay.com/photo/2016/03/05/19/02/hamburger-1238246_960_720.jpg',
        ingredients: ['beef', 'cheese', 'lettuce', 'tomato', 'onion', 'pickles'],
        containsEgg: false,
        isBestSeller: true,
    },
    {
        _id: '2',
        name: 'Chicken Tenders',
        price: 6.99,
        category: 'Appetizers',
        description: 'Crispy chicken tenders with your choice of dipping sauce.',
        image: 'https://cdn.pixabay.com/photo/2016/11/18/14/05/appetizer-1834646_960_720.jpg',
        ingredients: ['chicken', 'flour', 'egg', 'paprika', 'salt', 'pepper'],
        containsEgg: true,
        isBestSeller: false,
    },
    {
        _id: '3',
        name: 'Fried Shrimp',
        price: 8.99,
        category: 'Seafood',
        description: 'Golden fried shrimp served with cocktail sauce.',
        image: 'https://cdn.pixabay.com/photo/2016/11/18/14/05/appetizer-1834646_960_720.jpg',
        ingredients: ['shrimp', 'flour', 'egg', 'paprika', 'salt', 'pepper'],
        containsEgg: true,
        isBestSeller: false,
    },
    {
        _id: '4',
        name: 'Caesar Salad',
        price: 7.99,
        category: 'Salads',
        description: 'Crisp romaine lettuce with Caesar dressing and croutons.',
        image: 'https://cdn.pixabay.com/photo/2017/05/01/17/10/salad-2274362_960_720.jpg',
        ingredients: ['romaine lettuce', 'Caesar dressing', 'croutons', 'parmesan cheese'],
        containsEgg: true,
        isBestSeller: false,
    },
    {
        _id: '5',
        name: 'Margherita Pizza',
        price: 10.99,
        category: 'Pizza',
        description: 'Classic pizza with fresh mozzarella, tomatoes, and basil.',
        image: 'https://cdn.pixabay.com/photo/2017/12/09/08/18/pizza-3007395_960_720.jpg',
        ingredients: ['dough', 'tomato sauce', 'mozzarella cheese', 'tomato', 'basil'],
        containsEgg: false,
        isBestSeller: true,
    },
    {
        _id: '6',
        name: 'Spaghetti Carbonara',
        price: 12.99,
        category: 'Pasta',
        description: 'Pasta with pancetta, eggs, and parmesan cheese.',
        image: 'https://cdn.pixabay.com/photo/2017/11/08/22/18/spaghetti-2931846_960_720.jpg',
        ingredients: ['spaghetti', 'pancetta', 'egg', 'parmesan cheese', 'black pepper'],
        containsEgg: true,
        isBestSeller: false,
    },
    {
        _id: '7',
        name: 'Chocolate Cake',
        price: 4.99,
        category: 'Desserts',
        description: 'Rich chocolate cake with chocolate frosting.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['flour', 'sugar', 'cocoa powder', 'butter', 'eggs'],
        containsEgg: true,
        isBestSeller: false,
    },
    {
        _id: '8',
        name: 'Iced Tea',
        price: 2.99,
        category: 'Beverages',
        description: 'Refreshing iced tea with lemon.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['tea', 'water', 'sugar', 'lemon'],
        containsEgg: false,
        isBestSeller: false,
    },
    {
        _id: '9',
        name: 'Margarita',
        price: 7.99,
        category: 'Cocktails',
        description: 'Classic margarita with tequila, lime juice, and triple sec.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['tequila', 'lime juice', 'triple sec', 'salt'],
        containsEgg: false,
        isBestSeller: false,
    },
    {
        _id: '10',
        name: 'Mojito',
        price: 8.99,
        category: 'Cocktails',
        description: 'Refreshing mojito with rum, mint, lime, and soda water.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['rum', 'mint', 'lime', 'soda water', 'sugar'],
        containsEgg: false,
        isBestSeller: false,
    },
    {
        _id: '11',
        name: 'Fish Tacos',
        price: 9.99,
        category: 'Tacos',
        description: 'Crispy fish tacos with cabbage slaw and chipotle mayo.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['fish', 'tortillas', 'cabbage', 'mayo', 'chipotle'],
        containsEgg: false,
        isBestSeller: false,
    },
    {
        _id: '12',
        name: 'Pad Thai',
        price: 11.99,
        category: 'Noodles',
        description: 'Stir-fried noodles with shrimp, tofu, peanuts, and tamarind sauce.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['noodles', 'shrimp', 'tofu', 'peanuts', 'tamarind sauce'],
        containsEgg: false,
        isBestSeller: false,
    },
    {
        _id: '13',
        name: 'Pho',
        price: 10.99,
        category: 'Soups',
        description: 'Vietnamese noodle soup with beef, herbs, and broth.',
        image: 'https://cdn.pixabay.com/photo/2016/03/27/18/54/cake-1284541_960_720.jpg',
        ingredients: ['noodles', 'beef', 'herbs', 'broth'],
        containsEgg: false,
        isBestSeller: false,
    }
]